SET XACT_ABORT ON;

DECLARE @PlanningAuthorities TABLE
(
    [Name] NVARCHAR(255) NOT NULL,
    [Website] NVARCHAR(500) NOT NULL
);

INSERT INTO @PlanningAuthorities ([Name], [Website])
VALUES
    (N'Adur and Worthing Councils', N'https://planning.adur-worthing.gov.uk/online-applications'),
    (N'Babergh and Mid Suffolk District Councils', N'https://planning.baberghmidsuffolk.gov.uk/online-applications'),
    (N'Barnet Council', N'https://publicaccess.barnet.gov.uk/online-applications'),
    (N'Basildon Borough Council', N'https://planning.basildon.gov.uk/online-applications'),
    (N'Basingstoke and Deane Borough Council', N'https://publicaccess.basingstoke.gov.uk/online-applications'),
    (N'Bassetlaw District Council', N'https://publicaccess.bassetlaw.gov.uk/online-applications'),
    (N'Bedford Borough Council', N'https://publicaccess.bedford.gov.uk/online-applications'),
    (N'Blaby District Council', N'https://pa.blaby.gov.uk/online-applications'),
    (N'Blackpool Council', N'https://idoxpa.blackpool.gov.uk/online-applications'),
    (N'Bolsover District Council', N'https://publicaccess.bolsover.gov.uk/online-applications'),
    (N'Bolton Council', N'https://paplanning.bolton.gov.uk/online-applications'),
    (N'Bournemouth, Christchurch and Poole Council', N'https://boppa.poole.gov.uk/online-applications'),
    (N'Bracknell Forest Council', N'https://planapp.bracknell-forest.gov.uk/online-applications'),
    (N'City of Bradford Metropolitan District Council', N'https://planning.bradford.gov.uk/online-applications'),
    (N'Braintree District Council', N'https://publicaccess.braintree.gov.uk/online-applications'),
    (N'Brent Council', N'https://pa.brent.gov.uk/online-applications'),
    (N'Brentwood Borough Council', N'https://publicaccess.brentwood.gov.uk/online-applications'),
    (N'Brighton & Hove City Council', N'https://planningapps.brighton-hove.gov.uk/online-applications'),
    (N'Bristol City Council', N'https://pa.bristol.gov.uk/online-applications'),
    (N'Broadland and South Norfolk Councils', N'https://info.southnorfolkandbroadland.gov.uk/online-applications'),
    (N'Broads Authority', N'https://planning.broads-authority.gov.uk/online-applications'),
    (N'Bromsgrove District Council and Redditch Borough Council', N'https://publicaccess.bromsgroveandredditch.gov.uk/online-applications'),
    (N'Broxtowe Borough Council', N'https://publicaccess.broxtowe.gov.uk/online-applications'),
    (N'Buckinghamshire Council - Aylesbury Vale Area', N'https://publicaccess.aylesburyvaledc.gov.uk/online-applications'),
    (N'Buckinghamshire Council', N'https://pa-csb.buckinghamshire.gov.uk/online-applications'),
    (N'Buckinghamshire Council - Minerals and Waste Planning', N'https://publicaccess.buckscc.gov.uk/online-applications'),
    (N'Burnley Borough Council', N'https://publicaccess.burnley.gov.uk/online-applications'),
    (N'Bury Council', N'https://planning.bury.gov.uk/online-applications'),
    (N'Calderdale Council', N'https://portal.calderdale.gov.uk/online-applications'),
    (N'Cambridge City Council and South Cambridgeshire District Council', N'https://applications.greatercambridgeplanning.org/online-applications'),
    (N'Cambridgeshire County Council', N'https://planning.cambridgeshire.gov.uk/online-applications'),
    (N'Canterbury City Council', N'https://pa.canterbury.gov.uk/online-applications'),
    (N'Castle Point Borough Council', N'https://publicaccess.castlepoint.gov.uk/online-applications'),
    (N'Chelmsford City Council', N'https://publicaccess.chelmsford.gov.uk/online-applications'),
    (N'Cheltenham Borough Council', N'https://publicaccess.cheltenham.gov.uk/online-applications'),
    (N'Cheshire West and Chester Council', N'https://pa.cheshirewestandchester.gov.uk/online-applications'),
    (N'Chesterfield Borough Council', N'https://publicaccess.chesterfield.gov.uk/online-applications'),
    (N'Chichester District Council', N'https://publicaccess.chichester.gov.uk/online-applications'),
    (N'Chorley Council', N'https://planning.chorley.gov.uk/online-applications'),
    (N'City of Doncaster Council', N'https://planning.doncaster.gov.uk/online-applications'),
    (N'City of London Corporation', N'https://www.planning2.cityoflondon.gov.uk/online-applications'),
    (N'City of York Council', N'https://planningaccess.york.gov.uk/online-applications'),
    (N'Cornwall Council', N'https://planning.cornwall.gov.uk/online-applications'),
    (N'Cotswold District Council', N'https://publicaccess.cotswold.gov.uk/online-applications'),
    (N'Croydon Council', N'https://publicaccess3.croydon.gov.uk/online-applications'),
    (N'Cumberland Council', N'https://publicaccess.carlisle.gov.uk/online-applications'),
    (N'Darlington Borough Council', N'https://publicaccess.darlington.gov.uk/online-applications'),
    (N'Dartford Borough Council', N'https://publicaccess.dartford.gov.uk/online-applications'),
    (N'Derby City Council', N'https://eplanning.derby.gov.uk/online-applications'),
    (N'Derbyshire Dales District Council', N'https://planning.derbyshiredales.gov.uk/online-applications'),
    (N'Dover District Council', N'https://publicaccess.dover.gov.uk/online-applications'),
    (N'Durham County Council', N'https://publicaccess.durham.gov.uk/online-applications'),
    (N'Ealing Council', N'https://pam.ealing.gov.uk/online-applications'),
    (N'East Cambridgeshire District Council', N'https://pa.eastcambs.gov.uk/online-applications'),
    (N'East Devon District Council', N'https://planning.eastdevon.gov.uk/online-applications'),
    (N'East Herts District Council', N'https://publicaccess.eastherts.gov.uk/online-applications'),
    (N'East Lindsey District Council', N'https://publicaccess.e-lindsey.gov.uk/online-applications'),
    (N'East Suffolk Council', N'https://publicaccess.eastsuffolk.gov.uk/online-applications'),
    (N'Lewes and Eastbourne Councils', N'https://planningpa.lewes-eastbourne.gov.uk/online-applications'),
    (N'Ebbsfleet Development Corporation', N'https://applications.ebbsfleetdc.org.uk/online-applications'),
    (N'Enfield Council', N'https://planningandbuildingcontrol.enfield.gov.uk/online-applications'),
    (N'Epsom and Ewell Borough Council', N'https://eplanning.epsom-ewell.gov.uk/online-applications'),
    (N'Exeter City Council', N'https://publicaccess.exeter.gov.uk/online-applications'),
    (N'Forest of Dean District Council', N'https://publicaccess.fdean.gov.uk/online-applications'),
    (N'Gateshead Council', N'https://public.gateshead.gov.uk/online-applications'),
    (N'Gedling Borough Council', N'https://pawam.gedling.gov.uk/online-applications'),
    (N'Gloucester City Council', N'https://publicaccess.gloucester.gov.uk/online-applications'),
    (N'Gosport Borough Council', N'https://publicaccess.gosport.gov.uk/online-applications'),
    (N'Gravesham Borough Council', N'https://plan.gravesham.gov.uk/online-applications'),
    (N'Guildford Borough Council', N'https://publicaccess.guildford.gov.uk/online-applications'),
    (N'Halton Borough Council', N'https://pa.halton.gov.uk/online-applications'),
    (N'Harborough District Council', N'https://pa2.harborough.gov.uk/online-applications'),
    (N'Harlow Council', N'https://planningonline.harlow.gov.uk/online-applications'),
    (N'Hart District Council', N'https://publicaccess.hart.gov.uk/online-applications'),
    (N'Hastings Borough Council', N'https://publicaccess.hastings.gov.uk/online-applications'),
    (N'Havant Borough Council', N'https://planningpublicaccess.havant.gov.uk/online-applications'),
    (N'Hertsmere Borough Council', N'https://www6.hertsmere.gov.uk/online-applications'),
    (N'Hinckley and Bosworth Borough Council', N'https://pa.hinckley-bosworth.gov.uk/online-applications'),
    (N'Huntingdonshire District Council', N'https://publicaccess.huntingdonshire.gov.uk/online-applications'),
    (N'Isle of Wight Council', N'https://publicaccess.iow.gov.uk/online-applications'),
    (N'Borough Council of King''s Lynn and West Norfolk', N'https://online.west-norfolk.gov.uk/online-applications'),
    (N'Knowsley Metropolitan Borough Council', N'https://planapp.knowsley.gov.uk/online-applications'),
    (N'Lambeth Council', N'https://planning.lambeth.gov.uk/online-applications'),
    (N'Lancaster City Council', N'https://planning.lancaster.gov.uk/online-applications'),
    (N'Leeds City Council', N'https://publicaccess.leeds.gov.uk/online-applications'),
    (N'Lichfield District Council', N'https://planning.lichfielddc.gov.uk/online-applications'),
    (N'City of Lincoln Council', N'https://planning.lincoln.gov.uk/online-applications'),
    (N'London Borough of Bexley', N'https://pa.bexley.gov.uk/online-applications'),
    (N'London Borough of Bromley', N'https://searchapplications.bromley.gov.uk/online-applications'),
    (N'Hammersmith & Fulham Council', N'https://public-access.lbhf.gov.uk/online-applications'),
    (N'Lewisham Council', N'https://planning.lewisham.gov.uk/online-applications'),
    (N'Newham Council', N'https://pa.newham.gov.uk/online-applications'),
    (N'Tower Hamlets Council', N'https://development.towerhamlets.gov.uk/online-applications'),
    (N'Luton Council', N'https://planning.luton.gov.uk/online-applications'),
    (N'Maidstone Borough Council and Swale Borough Council', N'https://pa.midkent.gov.uk/online-applications'),
    (N'Maldon District Council', N'https://publicaccess.maldon.gov.uk/online-applications'),
    (N'Manchester City Council', N'https://pa.manchester.gov.uk/online-applications'),
    (N'Mansfield District Council', N'https://planning.mansfield.gov.uk/online-applications'),
    (N'Medway Council', N'https://publicaccess1.medway.gov.uk/online-applications'),
    (N'Melton Borough Council', N'https://pa.melton.gov.uk/online-applications'),
    (N'Mid Devon District Council', N'https://planning.middevon.gov.uk/online-applications'),
    (N'Mid Sussex District Council', N'https://pa.midsussex.gov.uk/online-applications'),
    (N'New Forest District Council', N'https://planning.newforest.gov.uk/online-applications'),
    (N'Newark and Sherwood District Council', N'https://publicaccess.newark-sherwooddc.gov.uk/online-applications'),
    (N'Newcastle-under-Lyme Borough Council', N'https://publicaccess.newcastle-staffs.gov.uk/online-applications'),
    (N'North East Derbyshire District Council', N'https://planapps-online.ne-derbyshire.gov.uk/online-applications'),
    (N'North East Lincolnshire Council', N'https://planninganddevelopment.nelincs.gov.uk/online-applications'),
    (N'North Herts Council', N'https://pa2.north-herts.gov.uk/online-applications'),
    (N'North Kesteven District Council', N'https://planningonline.n-kesteven.gov.uk/online-applications'),
    (N'North Norfolk District Council', N'https://idoxpa.north-norfolk.gov.uk/online-applications'),
    (N'North Northamptonshire Council - East Northamptonshire Area', N'https://publicaccess.east-northamptonshire.gov.uk/online-applications'),
    (N'North Northamptonshire Council - Wellingborough Area', N'https://publicaccess.wellingborough.gov.uk/online-applications'),
    (N'North Somerset Council', N'https://planning.n-somerset.gov.uk/online-applications'),
    (N'North Tyneside Council', N'https://idoxpublicaccess.northtyneside.gov.uk/online-applications'),
    (N'North Yorkshire Council (Craven)', N'https://publicaccess.cravendc.gov.uk/online-applications'),
    (N'North Yorkshire Council (Hambleton)', N'https://planning.hambleton.gov.uk/online-applications'),
    (N'North Yorkshire Council (Harrogate)', N'https://uniformonline.harrogate.gov.uk/online-applications'),
    (N'North Yorkshire Council (Richmondshire)', N'https://planning.richmondshire.gov.uk/online-applications'),
    (N'North Yorkshire Council (Ryedale)', N'https://planningregister.ryedale.gov.uk/caonline-applications'),
    (N'North Yorkshire Council (Scarborough)', N'https://planning.scarborough.gov.uk/online-applications'),
    (N'North Yorkshire Council (Selby)', N'https://public.selby.gov.uk/online-applications'),
    (N'Northumberland County Council', N'https://publicaccess.northumberland.gov.uk/online-applications'),
    (N'Norwich City Council', N'https://planning.norwich.gov.uk/online-applications'),
    (N'Nottingham City Council', N'https://publicaccess.nottinghamcity.gov.uk/online-applications'),
    (N'Oadby and Wigston Borough Council', N'https://pa.oadby-wigston.gov.uk/online-applications'),
    (N'Oldham Council', N'https://planningpa.oldham.gov.uk/online-applications'),
    (N'Oxford City Council', N'https://public.oxford.gov.uk/online-applications'),
    (N'Pendle Borough Council', N'https://publicaccess.pendle.gov.uk/online-applications'),
    (N'Peterborough City Council', N'https://planpa.peterborough.gov.uk/online-applications'),
    (N'Plymouth City Council', N'https://planning.plymouth.gov.uk/online-applications'),
    (N'Portsmouth City Council', N'https://publicaccess.portsmouth.gov.uk/online-applications'),
    (N'Reigate and Banstead Borough Council', N'https://planning.reigate-banstead.gov.uk/online-applications'),
    (N'Rochdale Borough Council', N'https://publicaccess.rochdale.gov.uk/online-applications'),
    (N'Rossendale Borough Council', N'https://publicaccess.rossendale.gov.uk/online-applications'),
    (N'Royal Borough of Greenwich', N'https://planning.royalgreenwich.gov.uk/online-applications'),
    (N'Royal Borough of Kingston upon Thames', N'https://publicaccess.kingston.gov.uk/online-applications'),
    (N'Royal Borough of Windsor and Maidenhead', N'https://publicaccess.rbwm.gov.uk/online-applications'),
    (N'Rushcliffe Borough Council', N'https://planningon-line.rushcliffe.gov.uk/online-applications'),
    (N'Rushmoor Borough Council', N'https://publicaccess.rushmoor.gov.uk/online-applications'),
    (N'Rutland County Council', N'https://publicaccess.rutland.gov.uk/online-applications'),
    (N'Sefton Council', N'https://pa.sefton.gov.uk/online-applications'),
    (N'Sevenoaks District Council', N'https://pa.sevenoaks.gov.uk/online-applications'),
    (N'Sheffield City Council', N'https://planningapps.sheffield.gov.uk/online-applications'),
    (N'Shropshire Council', N'https://pa.shropshire.gov.uk/online-applications'),
    (N'Solihull Metropolitan Borough Council', N'https://publicaccess.solihull.gov.uk/online-applications'),
    (N'Somerset Council (Area East)', N'https://publicaccess.mendip.gov.uk/online-applications'),
    (N'Somerset Council (Area South)', N'https://publicaccess.southsomerset.gov.uk/online-applications'),
    (N'Somerset Council (Somerset West and Taunton)', N'https://www1.somersetwestandtaunton.gov.uk/online-applications'),
    (N'South Downs National Park Authority', N'https://planningpublicaccess.southdowns.gov.uk/online-applications'),
    (N'South Gloucestershire Council', N'https://developments.southglos.gov.uk/online-applications'),
    (N'South Kesteven District Council', N'https://prod.publicaccess.southkesteven.gov.uk/online-applications'),
    (N'South Ribble Borough Council', N'https://publicaccess.southribble.gov.uk/online-applications'),
    (N'South Staffordshire Council', N'https://planning.sstaffs.gov.uk/online-applications'),
    (N'Southampton City Council', N'https://planningpublicaccess.southampton.gov.uk/online-applications'),
    (N'Southend-on-Sea City Council', N'https://publicaccess.southend.gov.uk/online-applications'),
    (N'Southwark Council', N'https://planning.southwark.gov.uk/online-applications'),
    (N'Spelthorne Borough Council', N'https://publicaccess.spelthorne.gov.uk/online-applications'),
    (N'St Helens Borough Council', N'https://publicaccess.sthelens.gov.uk/online-applications'),
    (N'Stafford Borough Council', N'https://www12.staffordbc.gov.uk/online-applications'),
    (N'Stevenage Borough Council', N'https://publicaccess.stevenage.gov.uk/online-applications'),
    (N'Stockton-on-Tees Borough Council', N'https://www.developmentmanagement.stockton.gov.uk/online-applications'),
    (N'Stoke-on-Trent City Council', N'https://planning.stoke.gov.uk/online-applications'),
    (N'Stroud District Council', N'https://publicaccess.stroud.gov.uk/online-applications'),
    (N'Surrey Heath Borough Council', N'https://publicaccess.surreyheath.gov.uk/online-applications'),
    (N'Sutton Council', N'https://planningregister.sutton.gov.uk/online-applications'),
    (N'Tameside Metropolitan Borough Council', N'https://publicaccess.tameside.gov.uk/online-applications'),
    (N'Teignbridge District Council', N'https://publicaccess.teignbridge.gov.uk/online-applications'),
    (N'Tendring District Council', N'https://idox.tendringdc.gov.uk/online-applications'),
    (N'Test Valley Borough Council', N'https://view-applications.testvalley.gov.uk/online-applications'),
    (N'Tewkesbury Borough Council', N'https://publicaccess.tewkesbury.gov.uk/online-applications'),
    (N'Thanet District Council', N'https://planning.thanet.gov.uk/online-applications'),
    (N'Three Rivers District Council', N'https://www3.threerivers.gov.uk/online-applications'),
    (N'Thurrock Council', N'https://regs.thurrock.gov.uk/online-applications'),
    (N'Torridge District Council', N'https://publicaccess.torridge.gov.uk/online-applications'),
    (N'Trafford Council', N'https://pa.trafford.gov.uk/online-applications'),
    (N'Tunbridge Wells Borough Council', N'https://twbcpa.midkent.gov.uk/online-applications'),
    (N'Uttlesford District Council', N'https://publicaccess.uttlesford.gov.uk/online-applications'),
    (N'Wakefield Council', N'https://planning.wakefield.gov.uk/online-applications'),
    (N'Warwick District Council', N'https://planningdocuments.warwickdc.gov.uk/online-applications'),
    (N'West Lancashire Borough Council', N'https://pa.westlancs.gov.uk/online-applications'),
    (N'West Oxfordshire District Council', N'https://publicaccess.westoxon.gov.uk/online-applications'),
    (N'West Suffolk Council', N'https://planning.westsuffolk.gov.uk/online-applications'),
    (N'Westminster City Council', N'https://idoxpa.westminster.gov.uk/online-applications'),
    (N'Wigan Council', N'https://planning.wigan.gov.uk/online-applications'),
    (N'Winchester City Council', N'https://planningapps.winchester.gov.uk/online-applications'),
    (N'Woking Borough Council', N'https://caps.woking.gov.uk/online-applications'),
    (N'City of Wolverhampton Council', N'https://planningonline.wolverhampton.gov.uk/online-applications'),
    (N'Wyre Council', N'https://publicaccess.wyre.gov.uk/online-applications'),
    (N'Wyre Forest District Council', N'https://planningpa.wyreforestdc.gov.uk/online-applications');

MERGE [dbo].[PlanningAuthority] AS [target]
USING @PlanningAuthorities AS [source]
    ON [target].[Website] = [source].[Website]
WHEN MATCHED AND [target].[Name] <> [source].[Name] THEN
    UPDATE SET [Name] = [source].[Name]
WHEN NOT MATCHED BY TARGET THEN
    INSERT ([Name], [Website])
    VALUES ([source].[Name], [source].[Website]);
